### ISSUE TITLE
看了下你的博客，很不错，我也想添加评论功能和文章底部的访问量信息

### ISSUE THREAD

**Issue by yanshigou** [HaoQChen/HaoQChen.github.io#31]
请问下需要在哪些文件中修改添加代码呢  谢谢！
我的博客地址 https://www.dogebug.cn/  哈哈 很简陋

**Comment by HaoQChen** [comment]
我的github的ReadMe有说怎么加的，你看一下～～

**Comment by yanshigou** [comment]
> 我的github上的自述有说怎么加的，你看一下~~

我昨晚上已经跟着修改了很多
很有帮助

**Comment by yanshigou** [comment]
> 我的github上的自述有说怎么加的，你看一下~~

只不过我暂时还没解决百度搜索与谷歌搜索的问题
我已经在head中添加了 我直接账号的谷歌、百度码

**Comment by yanshigou** [comment]
> > > 我的github上的自述有说怎么加的，你看一下~~
> > 
> > 
> > 只不过我暂时还没解决百度搜索与谷歌搜索的问题
> > 我已经在head中添加了 我直接账号的谷歌、百度码
> 
> 我现在都放弃百度搜索了，百度爬虫爬不了github，要弄coding之类的镜像，很麻烦。而且百度搜索添加了之后要等很久才行，谷歌也要等一天左右才会搜索得到。将md文件复制一份放到CSDN，然后在博客写一下自己的网站地址，流量还多一点。

好的谢谢！！
谷歌有时候我上不去，没有梯子，随缘吧
